### PR TITLE
Fixed loading of compressed sig files & Python 2.7 support.

### PR DESCRIPTION
**Pull request by crbednarz**
I'm not too familiar with python, but this seems to correct an exception I was having when trying to load newer compressed sig files.

### CODE REVIEW

**Comment by crbednarz** [comment]
I've also thrown in support for Python 2.7, which is what the Windows version ships with.

**Comment by thebabush** [comment]
First of all thanks for the PR ;) But I don't get why you did all of the import stuff. `builtins` is a package from [python future](http://python-future.org/) and it's exactly to support python 2.7 and python 3 together. It's basically a backport of some of python 3 features.

I see the point in not using an additional package, but it's my opinion that using `future` will pay back when Binja will switch to python 3. Btw, binja ships with python 2.7 also on Linux and Mac ;)

What I do on Linux is basically work in a virtualenv and do `pip install future`. Then, from the same venv, start Binja. This way it's going to pick up the additional packages. I never tried, but I think that something like that is possible on windows too...

**Comment by crbednarz** [comment]
Unfortunately in my experience the Windows version didn't want to play nice with installing future.
Seeing as this was a fresh install and I tried a number of workarounds, I assumed it was related to the embedded python included with Binja for Windows.

In the meantime this seemed like an acceptable temporary solution.

**Comment by crbednarz** [comment]
With that being said, I hadn't originally intended to include that commit in this pull request, so I'd be happy to reduce this down to just the first commit (for fixing compressed sig files), until I can verify the exact source of the "future" issue.

**Comment by thebabush** [comment]
The first commit is good :) I missed that bug.

As for `future`, it should really be a `pip install` away :/ I actually ran it successfully on my windows install. But I know venv support on windows is suboptimal.

**Comment by crbednarz** [comment]
Yeah, I'm not used to using pull requests, so it hadn't occurred to me that my commit after the request would be added to the request after the fact. I had intended to spend a bit more time investigating it.

For now I'm going to close this request and open a new one for a branch containing just that commit.

**Comment by thebabush** [comment]
Hey, if you find an easy way to work with binja + venvs in Windows, feel free to drop me a line so we can add detailed installation instructions to this repo ;)

**Pull request closed without merging**
